/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidade8;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliano
 */
public class AplicacaoMDI extends javax.swing.JFrame {

    /**
     * Creates new form AplicacaoMDI
     */
    public AplicacaoMDI() {
        initComponents();
        setBounds(200, 100, 400, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabelDesktopTitulo = new javax.swing.JLabel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        menuItemFuncionarioCadastro = new javax.swing.JMenuItem();
        menuItemFuncionarioExclusao = new javax.swing.JMenuItem();
        menuItemFuncionarioPesquisa = new javax.swing.JMenuItem();
        jMenuEmprego = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();
        menuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));

        jLabelDesktopTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDesktopTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDesktopTitulo.setText("SISTEMA DE RH");
        desktopPane.add(jLabelDesktopTitulo);
        jLabelDesktopTitulo.setBounds(100, 100, 200, 30);

        getContentPane().add(desktopPane);
        desktopPane.setBounds(0, 0, 400, 279);

        menuArquivo.setMnemonic('f');
        menuArquivo.setText("Arquivo");

        menuItemSair.setMnemonic('x');
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        menuBarPrincipal.add(menuArquivo);

        menuFuncionario.setText("Funcionário");

        menuItemFuncionarioCadastro.setText("Cadastro");
        menuItemFuncionarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionarioCadastroActionPerformed(evt);
            }
        });
        menuFuncionario.add(menuItemFuncionarioCadastro);

        menuItemFuncionarioExclusao.setText("Exclusão");
        menuFuncionario.add(menuItemFuncionarioExclusao);

        menuItemFuncionarioPesquisa.setText("Pesquisa");
        menuItemFuncionarioPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionarioPesquisaActionPerformed(evt);
            }
        });
        menuFuncionario.add(menuItemFuncionarioPesquisa);

        menuBarPrincipal.add(menuFuncionario);

        jMenuEmprego.setText("Emprego");
        jMenuEmprego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEmpregoMouseClicked(evt);
            }
        });
        menuBarPrincipal.add(jMenuEmprego);

        menuAjuda.setMnemonic('h');
        menuAjuda.setText("Ajuda");

        menuItemSobre.setMnemonic('a');
        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemSobre);

        menuBarPrincipal.add(menuAjuda);

        setJMenuBar(menuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemFuncionarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionarioCadastroActionPerformed
        JFrameFuncionarioCadastro frameFuncionarioCadastro = new JFrameFuncionarioCadastro();
        frameFuncionarioCadastro.setVisible(true);
    }//GEN-LAST:event_menuItemFuncionarioCadastroActionPerformed

    private void menuItemFuncionarioPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionarioPesquisaActionPerformed
        JFrameFuncionarioPesquisa frameFuncionarioPesquisa = new JFrameFuncionarioPesquisa();
        frameFuncionarioPesquisa.setVisible(true);
    }//GEN-LAST:event_menuItemFuncionarioPesquisaActionPerformed

    private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
        JOptionPane.showMessageDialog(this, "Exemplo de aplicação\nutilizando os componentes SWING\ne o driver JDBC do PostgreSQL\nno Netbeans IDE.");
    }//GEN-LAST:event_menuItemSobreActionPerformed

    private void jMenuEmpregoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEmpregoMouseClicked
        JFrameEmprego frameEmprego = new JFrameEmprego();
        frameEmprego.setVisible(true);
    }//GEN-LAST:event_jMenuEmpregoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacaoMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacaoMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacaoMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacaoMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacaoMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabelDesktopTitulo;
    private javax.swing.JMenu jMenuEmprego;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenuItem menuItemFuncionarioCadastro;
    private javax.swing.JMenuItem menuItemFuncionarioExclusao;
    private javax.swing.JMenuItem menuItemFuncionarioPesquisa;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSobre;
    // End of variables declaration//GEN-END:variables

    

}
