/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidade8;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Transaction;
import org.hibernate.classic.Session;

/**
 *
 * @author Juliano
 */
public class JFrameEmprego extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegiao
     */
    public JFrameEmprego() {
        initComponents();
        setBounds(200, 100, 500, 420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTítulo = new javax.swing.JLabel();
        jLabelEmprego = new javax.swing.JLabel();
        jTextFieldEmprego = new javax.swing.JTextField();
        jLabelSalarioMaximo = new javax.swing.JLabel();
        jLabelSalarioMinimo = new javax.swing.JLabel();
        jTextFieldSalarioMaximo = new javax.swing.JTextField();
        jTextFieldSalarioMinimo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmprego = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 420));
        getContentPane().setLayout(null);

        jLabelTítulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTítulo.setText("EMPREGO");
        getContentPane().add(jLabelTítulo);
        jLabelTítulo.setBounds(10, 11, 53, 14);

        jLabelEmprego.setText("Emprego");
        getContentPane().add(jLabelEmprego);
        jLabelEmprego.setBounds(10, 40, 120, 14);
        getContentPane().add(jTextFieldEmprego);
        jTextFieldEmprego.setBounds(140, 40, 170, 25);

        jLabelSalarioMaximo.setText("Salário máximo R$");
        getContentPane().add(jLabelSalarioMaximo);
        jLabelSalarioMaximo.setBounds(10, 120, 120, 14);

        jLabelSalarioMinimo.setText("Salário mínimo R$");
        getContentPane().add(jLabelSalarioMinimo);
        jLabelSalarioMinimo.setBounds(10, 80, 120, 14);
        getContentPane().add(jTextFieldSalarioMaximo);
        jTextFieldSalarioMaximo.setBounds(140, 120, 120, 25);
        getContentPane().add(jTextFieldSalarioMinimo);
        jTextFieldSalarioMinimo.setBounds(140, 80, 120, 25);

        jTableEmprego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Emprego", "Salário mínimo", "Salário máximo"
            }
        ));
        jScrollPane1.setViewportView(jTableEmprego);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 470, 100);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(230, 160, 100, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(340, 160, 100, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(10, 160, 100, 23);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(120, 160, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        List resultado = null;
        Session sessao = null;
        try {
            sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();
            int id;
            id = Integer.parseInt(JOptionPane.showInputDialog(null, "Código do emprego a ser ALTERADO:", "Editar", JOptionPane.PLAIN_MESSAGE));
            org.hibernate.Query query = sessao.createQuery("FROM Emprego WHERE id = " + id);
            resultado = query.list();
            for (Object obj : resultado) {
                Emprego emp = (Emprego) obj;
                emp.setId(id);
                emp.setName(jTextFieldEmprego.getText());
                emp.setMinsalary(Double.parseDouble(jTextFieldSalarioMinimo.getText()));
                emp.setMaxsalary(Double.parseDouble(jTextFieldSalarioMaximo.getText()));
                sessao.update(emp);
                transacao.commit();
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        List<Emprego> resultado = new ArrayList();
        String sql = "FROM Emprego "
                + "WHERE name LIKE '%" + jTextFieldEmprego.getText() + "%' "
                + "ORDER BY id";
        jTableEmprego.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableEmprego.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableEmprego.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableEmprego.getColumnModel().getColumn(3).setPreferredWidth(100);
        DefaultTableModel modelo = (DefaultTableModel) jTableEmprego.getModel();
        modelo.setNumRows(0);

        try {
            Session sessao = HibernateUtil.getSessionFactory().openSession();
            org.hibernate.Query query = sessao.createQuery(sql);
            resultado = query.list();
            for (int i = 0; i < resultado.size(); i++) {
                Emprego emprego = resultado.get(i);
                modelo.addRow(new Object[]{emprego.getId(), emprego.getName(), emprego.getMinsalary(), emprego.getMaxsalary()});
            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Session sessao = null;
        try {
            sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();
            Emprego job = new Emprego();
            job.setName(jTextFieldEmprego.getText());
            job.setMaxsalary(Double.parseDouble(jTextFieldSalarioMaximo.getText()));
            job.setMinsalary(Double.parseDouble(jTextFieldSalarioMinimo.getText()));
            sessao.save(job);
            transacao.commit();
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        } finally {
            sessao.close();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        List resultado = null;
        Session sessao = null;
        try {
            sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();
            int id;
            id = Integer.parseInt(JOptionPane.showInputDialog(null, "Código do emprego a ser EXCLUÍDO:", "Excluir", JOptionPane.PLAIN_MESSAGE));
            org.hibernate.Query query = sessao.createQuery("FROM Emprego WHERE id = " + id);
            resultado = query.list();
            for (Object obj : resultado) {
                Emprego emp = (Emprego) obj;
                sessao.delete(emp);
                transacao.commit();
                JOptionPane.showMessageDialog(null, "Cadastro excluído com sucesso!");
            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmprego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmprego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmprego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmprego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmprego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelEmprego;
    private javax.swing.JLabel jLabelSalarioMaximo;
    private javax.swing.JLabel jLabelSalarioMinimo;
    private javax.swing.JLabel jLabelTítulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmprego;
    private javax.swing.JTextField jTextFieldEmprego;
    private javax.swing.JTextField jTextFieldSalarioMaximo;
    private javax.swing.JTextField jTextFieldSalarioMinimo;
    // End of variables declaration//GEN-END:variables

}
