/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidade8;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliano
 */
public class JFrameFuncionarioCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameFuncionarioCadastro
     */
    public JFrameFuncionarioCadastro() {
        initComponents();
        setBounds(200, 100, 350, 420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFuncao = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelSobrenome = new javax.swing.JLabel();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelFone = new javax.swing.JLabel();
        jTextFieldFone = new javax.swing.JTextField();
        jLabelContratacao = new javax.swing.JLabel();
        jTextFieldContratacao = new javax.swing.JTextField();
        jLabelFuncao = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabelComissao = new javax.swing.JLabel();
        jTextFieldComissao = new javax.swing.JTextField();
        jLabelChefe = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxChefe = new javax.swing.JComboBox<>();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jComboBoxFuncao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTitulo.setText("CADASTRO DE FUNCIONÁRIO");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(10, 10, 158, 14);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(10, 30, 120, 14);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(140, 30, 170, 25);

        jLabelSobrenome.setText("Sobrenome *");
        getContentPane().add(jLabelSobrenome);
        jLabelSobrenome.setBounds(10, 60, 120, 14);
        getContentPane().add(jTextFieldSobrenome);
        jTextFieldSobrenome.setBounds(140, 60, 170, 25);

        jLabelEmail.setText("E-mail *");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(10, 90, 120, 14);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(140, 90, 170, 25);

        jLabelFone.setText("Fone");
        getContentPane().add(jLabelFone);
        jLabelFone.setBounds(10, 120, 120, 14);
        getContentPane().add(jTextFieldFone);
        jTextFieldFone.setBounds(140, 120, 100, 25);

        jLabelContratacao.setText("Data de contratação *");
        getContentPane().add(jLabelContratacao);
        jLabelContratacao.setBounds(10, 150, 120, 14);
        getContentPane().add(jTextFieldContratacao);
        jTextFieldContratacao.setBounds(140, 150, 100, 25);

        jLabelFuncao.setText("Função *");
        getContentPane().add(jLabelFuncao);
        jLabelFuncao.setBounds(10, 180, 120, 14);

        jLabelSalario.setText("Salário");
        getContentPane().add(jLabelSalario);
        jLabelSalario.setBounds(10, 210, 120, 14);
        getContentPane().add(jTextFieldSalario);
        jTextFieldSalario.setBounds(140, 210, 100, 25);

        jLabelComissao.setText("Comissão");
        getContentPane().add(jLabelComissao);
        jLabelComissao.setBounds(10, 240, 120, 14);
        getContentPane().add(jTextFieldComissao);
        jTextFieldComissao.setBounds(140, 240, 100, 25);

        jLabelChefe.setText("Chefe");
        getContentPane().add(jLabelChefe);
        jLabelChefe.setBounds(10, 270, 120, 14);

        jLabelDepartamento.setText("Departamento");
        getContentPane().add(jLabelDepartamento);
        jLabelDepartamento.setBounds(10, 300, 120, 14);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(140, 340, 100, 25);

        jComboBoxChefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "19", "20" }));
        getContentPane().add(jComboBoxChefe);
        jComboBoxChefe.setBounds(140, 270, 170, 25);

        jComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Sales", "Holder", "Commercial", "TI", "Accounting", "Financial", "Purchasing", "Human Resources", "Engineering", "Direction" }));
        jComboBoxDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDepartamento);
        jComboBoxDepartamento.setBounds(140, 300, 170, 25);

        jComboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seller", "Support", "Analyst", "Programmer", "Counter", "Engineer", "Administrator", "Secretary", "Director", "President", "Intern" }));
        jComboBoxFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncaoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFuncao);
        jComboBoxFuncao.setBounds(140, 180, 170, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        //DECLARAÇÃO E INICIALIZAÇÃO DAS VARIÁVEIS
        String nome = jTextFieldNome.getText();
	String sobrenome = jTextFieldSobrenome.getText();        
	String email = jTextFieldEmail.getText();
	String fone = jTextFieldFone.getText();
	String dataContratacao = jTextFieldContratacao.getText();
	String funcao = Unidade8.selectJobId((String)jComboBoxFuncao.getSelectedItem());
        System.out.println (funcao);
        String salario = jTextFieldSalario.getText();
	String comissao = jTextFieldComissao.getText();
	String chefe = (String)jComboBoxChefe.getSelectedItem();
	String departamento = Unidade8.selectDepartmentId ((String)jComboBoxDepartamento.getSelectedItem());
        String obrigatorios = "";
        boolean controle = false;
        
        //VALIDAÇÃO DAS INFORMAÇÕES
        if (sobrenome.equals("")) {
            obrigatorios = obrigatorios+"\n - Sobrenome";
            controle = true;
        }
        if (email.equals("")) {
            obrigatorios = obrigatorios+"\n - E-mail";
            controle = true;
        }
        if (dataContratacao.equals("")) {
            obrigatorios = obrigatorios+"\n - Data de contratação";
            controle = true;
        }
        if (chefe.equals("Nenhum")) {
            chefe = "";
        }
        if (departamento.equals("Nenhum")) {
            departamento = "";
        }
        
        //VERIFICAÇÃO DA CHAMADA DA INSERÇÃO OU NÃO
        if (controle == false) {
            Unidade8.insertEmployee (nome, sobrenome, email, fone, dataContratacao, funcao, salario, comissao, chefe, departamento);
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatórios:"+obrigatorios);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDepartamentoActionPerformed

    private void jComboBoxFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFuncaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFuncionarioCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFuncao;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxChefe;
    private javax.swing.JComboBox<String> jComboBoxDepartamento;
    private javax.swing.JComboBox<String> jComboBoxFuncao;
    private javax.swing.JLabel jLabelChefe;
    private javax.swing.JLabel jLabelComissao;
    private javax.swing.JLabel jLabelContratacao;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldComissao;
    private javax.swing.JTextField jTextFieldContratacao;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
